view/post/urls.py
from django.urls import path

from post.views import PostWriteView, PostDetailView, PostUpdateView, PostDeleteView, PostListView, PostListAPI


app_name = 'post'

urlpatterns = [
    path('write/', PostWriteView.as_view(), name='write'),
    path('detail/', PostDetailView.as_view(), name='detail'),
    path('update/', PostUpdateView.as_view(), name='update'),
    path('delete/', PostDeleteView.as_view(), name='delete'),
    path('list/', PostListView.as_view(), name='list'),
    path('list/<int:page>/', PostListAPI.as_view(), name='list-api'),
]

view/travel/urls.py
from django.urls import path

from travel.views import TravelWriteView, TravelDetailView

app_name = 'travel'

urlpatterns = [
    path('write/', TravelWriteView.as_view(), name='write'),
    path('detail/', TravelDetailView.as_view(), name='detail')
]

view/view/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from exhibition.views import ExhibitionFileDownloadView
from main.views import MainView
from view.views import StudentRegisterView, StudentResultView, StudentRegisterFormView, MemberRegisterFormView, \
    MemberRegisterView, MemberResultView, StudentRegister2FormView, StudentRegister2View, StudentResult2View, \
    ProductDetailAPI, ProductDetailView


class TravelResultView:
    pass


urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('post/', include('post.urls')),
    path('student/register/form/', StudentRegisterFormView.as_view(), name='student-register-form'),
    path('student/register/', StudentRegisterView.as_view(), name='student-register'),
    path('student/result/', StudentResultView.as_view(), name='student-result'),
    path('member/register/form/', MemberRegisterFormView.as_view(), name='member-register-form'),
    path('member/register/', MemberRegisterView.as_view(), name='member-register'),
    path('member/result', MemberResultView.as_view(), name='member-result'),
    path('student/register2/form/', StudentRegister2FormView.as_view(), name='student-register2-form'),
    path('student/register2/', StudentRegister2View.as_view(), name='student-register2'),
    path('student/result2/', StudentResult2View.as_view(), name='student-result2'),
    # path('travel/', include('travel.urls')),
    path('product/detail/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:product_id>/', ProductDetailAPI.as_view(),name='product-detail'),
    path('exhibition/', include('exhibition.urls')),
    path('notification/', include('notification.urls')),
    path('upload/<path:file_path>/', ExhibitionFileDownloadView.as_view(), name='download'),
    path('', MainView.as_view()),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

view/travel/models.py
from django.db import models

class Travel(models.Model):
    travel_budget = models.BigIntegerField(null=False, default=0)
    travel_destination = models.TextField(null=False, blank=False)
    travel_date = models.TextField(null=False, blank=False)
    # False = 예약 안함, True = 예약 함.
    travel_hotel_reservation = models.BooleanField(null=False, default=False)

    class Meta:
        db_table = 'tbl_travel'

    def get_absolute_url(self):
        return f'/travel/detail/?id={self.id}'

view/travel/views.py
from django.shortcuts import render, redirect
from django.views import View

from travel.models import Travel


class TravelWriteView(View):
    def get(self, request):
        return render(request, 'travel/write.html')

    def post(self, request):
        data = request.POST
        data = {
            'travel_budget' : data['travel-budget'],
            'travel_destination' : data['travel-destination'],
            'travel_date' : data['travel-date'],
            'travel_hotel_reservation' : data['travel-hotel-reservation']
        }

        travel = Travel.objects.create(**data)

        return redirect(travel.get_absolute_url())

class TravelDetailView(View):
    def get(self, request):
        print("들어옴")
        travel = Travel.objects.get(id=request.GET['id'])
        context = {
            'travel': travel
        }

        return render(request, 'travel/detail.html', context)

view/templates/travel/detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TRAVEL-DETAIL</title>
    <style>
        table {
            border : 1px solid black;
            border-collapse : collapse;
            width: 600px;
            margin: 0 auto;
            text-align: center;
        }
        
        tr, th {
            border: 1px solid black;
        }
    </style>
</head>
<body>

    <table>
        <tr>
            <th>여행지</th>
            <th>여행일수</th>
            <th>여행예산</th>
            <th>호텔예약여부</th>
        </tr>
        <tr>
            <td>{{ travel.travel_destination }}</td>
            <td>{{ travel.travel_date }}</td>
            <td>{{ travel.travel_budget }}</td>
            <td>{{ travel.travel_hotel_reservation }}</td>
        </tr>
    </table>
    <p>{{ travel.travel_date }}일차 : {{ travel.travel_destination }}</p>
</body>
</html>

view/templates/travel/write.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'post/css/header.css' %}">
    <title>TRAVEL-WRITE</title>
</head>
<body>
<form action="{% url 'travel:write' %}" method="post" name="write-form">
    {% csrf_token %}
    <input type="text" name="travel-destination" placeholder="여행 장소">
    <input type="text" name="travel-budget" placeholder="여행 예산">
    <input type="text" name="travel-date" placeholder="여행 일수">
    <input type="text" name="travel-hotel-reservation" placeholder="호텔 예약 여부">
    <button>완료</button>
</form>
</body>
</html>