view/member/urls.py
from django.contrib import admin
from django.urls import path, include

from member.views import MemberJoinView, MemberLoginView, MemberLogoutView, AdminMemberLoginView, AdminMainView, \
    AdminMainUserView, AdminMainNotificationView, AdminMainInquiryView, AdminMainPaymentView, AdminMainExhibitionView, \
    AdminMainNotificationWriteView, AdminNotificationListAPI, soft_delete, AdminMainUserListAPI, translate, \
    AdminMainExhibitionListAPI, soft_delete_exhibition

app_name = 'member'

urlpatterns = [
    path('join/', MemberJoinView.as_view(), name='join'),
    path('login/', MemberLoginView.as_view(), name='login'),
    path('logout/', MemberLogoutView.as_view(), name='logout'),
    path('admin_login/', AdminMemberLoginView.as_view(), name='admin_login'),
    path('admin_main/', AdminMainView.as_view(), name='admin_main'),
    path('admin_main_user/', AdminMainUserView.as_view(), name='admin_main_user'),
    path('admin_main_user/<int:page>/', AdminMainUserListAPI.as_view(), name='admin_main_user_list'),
    path('admin_main_notification/', AdminMainNotificationView.as_view(), name='admin_main_notification'),
    path('admin_main_inquiry/', AdminMainInquiryView.as_view(), name='admin_main_inquiry'),
    path('admin_main_payment/', AdminMainPaymentView.as_view(), name='admin_main_payment'),
    path('admin_main_exhibition/', AdminMainExhibitionView.as_view(), name='admin_main_exhibition'),
    path('admin_main_exhibition/<int:page>/', AdminMainExhibitionListAPI.as_view(), name='admin_main_exhibition_list'),
    path('admin_main_notification_write/', AdminMainNotificationWriteView.as_view(), name='admin_main_notification_write'),
    path('admin_main_notification/<int:page>/', AdminNotificationListAPI.as_view(), name='admin_main_notification_list'),
    path('soft_delete/', soft_delete, name='soft_delete'),
    path('translate/', translate, name='translate'),
    path('soft_delete_exhibition/', soft_delete_exhibition, name='soft_delete_exhibition')

]

view/post/urls.py
from django.urls import path

from post.views import PostWriteView, PostDetailView, PostUpdateView, PostDeleteView, PostListView, PostListAPI


app_name = 'post'

urlpatterns = [
    path('write/', PostWriteView.as_view(), name='write'),
    path('detail/', PostDetailView.as_view(), name='detail'),
    path('update/', PostUpdateView.as_view(), name='update'),
    path('delete/', PostDeleteView.as_view(), name='delete'),
    path('list/', PostListView.as_view(), name='list'),
    path('list/<int:page>/', PostListAPI.as_view(), name='list-api'),
]

view/view/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from exhibition.views import ExhibitionFileDownloadView
from main.views import MainView
from view.views import StudentRegisterView, StudentResultView, StudentRegisterFormView, MemberRegisterFormView, \
    MemberRegisterView, MemberResultView, StudentRegister2FormView, StudentRegister2View, StudentResult2View, \
    ProductDetailAPI, ProductDetailView


class TravelResultView:
    pass


urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('post/', include('post.urls')),
    path('student/register/form/', StudentRegisterFormView.as_view(), name='student-register-form'),
    path('student/register/', StudentRegisterView.as_view(), name='student-register'),
    path('student/result/', StudentResultView.as_view(), name='student-result'),
    path('member/register/form/', MemberRegisterFormView.as_view(), name='member-register-form'),
    path('member/register/', MemberRegisterView.as_view(), name='member-register'),
    path('member/result', MemberResultView.as_view(), name='member-result'),
    path('student/register2/form/', StudentRegister2FormView.as_view(), name='student-register2-form'),
    path('student/register2/', StudentRegister2View.as_view(), name='student-register2'),
    path('student/result2/', StudentResult2View.as_view(), name='student-result2'),
    # path('travel/', include('travel.urls')),
    path('product/detail/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:product_id>/', ProductDetailAPI.as_view(),name='product-detail'),
    path('exhibition/', include('exhibition.urls')),
    path('notification/', include('notification.urls')),
    path('upload/<path:file_path>/', ExhibitionFileDownloadView.as_view(), name='download'),
    path('', MainView.as_view()),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

view/post/models.py
from django.db import models

from member.models import Member
from post.managers import PostManager


class Post(models.Model):
    post_title = models.CharField(max_length=50, null=False, blank=False)
    post_content = models.CharField(max_length=3000, null=False, blank=False)
    post_view_count = models.BigIntegerField(null=False, default=0)
    post_status = models.BooleanField(default=True)
    member = models.ForeignKey(Member, on_delete=models.PROTECT)

    objects = models.Manager()
    enabled_objects = PostManager()

    class Meta:
        db_table = 'tbl_post'
        ordering = ['-id']

    def get_absolute_url(self):
        return f'/post/detail/?id={self.id}'

class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT, null=False)
    path = models.ImageField(null=False, blank=False, upload_to='post/%Y/%m/%d/')

    class Meta:
        db_table = 'tbl_post_file'

view/post/views.py
import math

from django.db import transaction
from django.db.models import F
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.response import Response
from rest_framework.views import APIView

from member.models import Member
from post.models import Post, PostFile


class PostWriteView(View):
    def get(self, request):
        return render(request, 'post/write.html')

    @transaction.atomic
    def post(self, request):
        data = request.POST
        # input 태그 하나당 파일 1개일때
        # file = request.FILES


        # input 태그 하나에 여러 파일일 때 (multiple), getlist('{input태그 name값}')
        files = request.FILES.getlist('upload-file')

        member = Member(**request.session['member'])

        data = {
            'post_title': data['post-title'],
            'post_content': data['post-content'],
            'member': member
        }
        post = Post.objects.create(**data)

        for file in files:
            PostFile.objects.create(post=post, path=file)

        return redirect(post.get_absolute_url())


class PostDetailView(View):
    def get(self, request):
        post = Post.objects.get(id=request.GET['id'])

        post.post_view_count += 1
        post.save(update_fields=['post_view_count'])

        context = {
            'post': post,
            'post_files' : list(post.postfile_set.all())
        }
        return render(request, 'post/detail.html', context)


class PostUpdateView(View):
    def get(self, request):
        post = Post.objects.get(id=request.GET['id'])
        return render(request, "post/update.html", {'post': post})

    def post(self, request):
        data = request.POST

        post_id = data['id']
        post = Post.objects.get(id=post_id)

        post.post_title = data['post-title']
        post.post_content = data['post-content']
        post.save(update_fields=['post_title', 'post_content'])

        return redirect(post.get_absolute_url())


class PostDeleteView(View):
    def get(self, request):
        Post.objects.filter(id=request.GET['id']).update(post_status=False)
        # post = Post.objects.get(id=request.GET['id'])
        # post.post_status = False
        # post.save(update_fields=['post_status'])
        return redirect('/post/list')


class PostListView(View):
    def get(self, request):
        return render(request, 'post/list.html')


class PostListAPI(APIView):
    def get(self, request, page):
        row_count = 5

        offset = (page - 1) * row_count
        limit = page * row_count
        columns = [
            'id',
            'post_title',
            'post_content',
            'post_view_count',
            'member_name'
        ]
        posts = Post.enabled_objects\
                    .annotate(member_name=F('member__member_name'))\
                    .values(*columns)[offset:limit]

        has_next = Post.enabled_objects.filter()[limit:limit + 1].exists()

        post_info = {
            'posts': posts,
            'hasNext': has_next
        }

        return Response(post_info)

view/templates/post/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'public/css/header.css' %}">
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{#    {% if request.session.member %}#}
{#        {% include 'fix/header1.html' %}#}
{#    {% elif 조건식 %}#}
{#        {% include 'fix/header2.html' %}#}
{#    {% else %}#}
{#        {% include 'fix/header3.html' %}#}
{#    {% endif %}#}
    {% include 'fix/header.html' %}
    {% block content %}{% endblock %}
</body>
    {% block js %}{% endblock %}
</html>

view/templates/post/detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>POST-DETAIL</title>
    <link rel="stylesheet" href="{% static 'post/css/header.css' %}">
    <style>
        table {
            border : 1px solid black;
            border-collapse : collapse;
            width: 600px;
            margin: 0 auto;
            text-align: center;
        }
        
        tr, th {
            border: 1px solid black;
        }
    </style>
</head>
<body>
<header>
    <div>
        <div>
            <p>
                <strong>{{ request.session.member.member_name }}님 환영합니다.😊</strong>
            </p>
        </div>
        <div>
            <a href="{% url 'member:logout' %}"></a>
        </div>
    </div>
</header>
{#    querystring을 쓸때는 url을 붙여 쓰면 안됨.#}

    <a href="/post/update/?id={{ post.id }}">수정하기</a>
{#    <a href="{% url 'post:update' post_id=post.id post_test=1 %}">수정하기</a>#}
{#    <a href="/post/delete/?id={{ post.id }}">삭제하기</a>#}
    <table>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>내용</th>
            <th>작성자</th>
            <th>조회수</th>
        </tr>
        <tr>
            <td>{{ post.id }}</td>
            <td>{{ post.post_title }}</td>
            <td>{{ post.post_content }}</td>
            <td>{{ post.member.member_name }}</td>
            <td>{{ post.post_view_count }}</td>
        </tr>
    </table>
    {% for post_file in post_files %}
        <img src="/upload/{{ post_file.path }}">
    {% endfor %}
    
</body>
</html>

view/templates/post/list.html
{% extends 'post/base.html' %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'post/css/table.css' %}">
{% endblock %}

{% block title %}LIST{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>조회수</th>
        </tr>
    </table>
    <button id="more">더보기</button>
{% endblock %}

{% block js %}
    <script src="{% static 'post/js/list.js' %}"></script>
{% endblock %}

view/templates/post/update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>POST-UPDATE</title>
</head>
<body>
<header>
    <div>
        <div>
            <p>
                <strong>{{ request.session.member.member_name }}님 환영합니다🤩</strong>
            </p>
        </div>
        <div>
            <a href="{% url 'member:logout' %}">로그아웃</a>
        </div>
    </div>
</header>
<form action="{% url 'post:update' %}" method="post" name="update-form">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ post.id }}">
    <input type="text" name="post-title" placeholder="게시글 제목" value="{{ post.post_title }}">
    <p>게시글 내용</p>
    <textarea name="post-content" cols="30" rows="10" style="resize: none">{{ post.post_content }}</textarea>
    <button>완료</button>
</form>
</body>
</html>

view/templates/post/write.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'post/css/header.css' %}">
    <title>POST-WRITE</title>
</head>
<body>
<header>
    <div>
        <div>
            <p>
                <strong>{{ request.session.member.member_name }}님 환영합니다.😊</strong>
            </p>
        </div>
        <div>
            <a href="{% url 'member:logout' %}"></a>
        </div>
    </div>
</header>
{#multipart/form-data 를 사용해야 file이 업로드가 됨#}
<form action="{% url 'post:write' %}" method="post" name="write-form" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="post-title" placeholder="게시글 제목">
    <p>게시글 내용</p>
    <textarea name="post-content" cols="30" rows="10" style="resize: none"></textarea>
    <input type="file" name="upload-file" multiple>
    <button>완료</button>
</form>
</body>
</html>